<?php

/*
 * Implements hook_init()
 */

//function rocola_core_init() {
//  require '/home/mazpes5/www/rocola/sites/all/libraries/vendor/autoload.php';
//
//  $api = new SpotifyWebAPI\Session(
//      'cf9abaf802f247c3b192135c12115b23', 
//      '54ed0d23207e473b9de9d4dfc2a7c720'
//  );
//
//  //global $api;
//  //$session = new SpotifyWebAPI\SpotifyWebAPI();
//
//  $api->requestCredentialsToken();
//  $accessToken = $api->getAccessToken();
//  
//  print_r($api->getClientId());
//  header('Location: http://www.mazpesca.com/rocola/spotify/playlist');
//  //die();
//}

/*
 * Implements hook_menu()
 */

function rocola_core_menu() {

  $items['spotify/playlist'] = array(
    'title' => 'La Mona Jukebox',
    'page callback' => 'playlist_page',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/rocola/manage'] = array(
    'title' => 'My Rocola Settings',
    'description' => 'Manage My Rocola Settings',
    'access arguments' => array('access administration pages'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rocola_core_form'),
  );
  
  return $items;
}

function rocola_core_form($form, &$form_state){
  
  $form = array();
  
  $form['overview'] = array(
    '#markup' => t('This interface allows administrators to manage Spotify API.'),
    '#prefix' => '<p>',
    '#suffix' => '</p>',
  );
  /*
   * View Tab
   */
  $form['client_id'] = array(
    '#title' => t('CLIENT ID'),
    '#description' => t('Use your client id.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('spotify_client_id' ,''),
  );
  
  $form['client_secret'] = array(
    '#title' => t('CLIENT SECRET'),
    '#description' => t('Use your client secret.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('spotify_client_secret' ,''),
  );
  
  $form['user_id'] = array(
    '#title' => t('USER ID'),
    '#description' => t('Use your User ID.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('spotify_user_id' ,''),
  );
  
  $form['playlist_id_selection'] = array(
    '#title' => t('Playlist Selection'),
    '#description' => t('Use the playlist for selection.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('spotify_playlist_id_selection' ,''),
  );
  
  $form['playlist_id_queue'] = array(
    '#title' => t('Playlist Queue'),
    '#description' => t('Use the playlist for playing.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('spotify_playlist_id_queue' ,''),
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  
  return $form;
}

function rocola_core_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  variable_set('spotify_client_id', $form_state['values']['client_id']);
  variable_set('spotify_client_secret', $form_state['values']['client_secret']);
  variable_set('spotify_user_id', $form_state['values']['user_id']);
  variable_set('spotify_playlist_id_selection', $form_state['values']['playlist_id_selection']);
  variable_set('spotify_playlist_id_queue', $form_state['values']['playlist_id_queue']);
  
  drupal_set_message(t('Your configuration has been saved.'));
}

function playlist_page() {
  
  $output = '';
  
  $output .= '<h1>La Mona Rocks</h1>';
  
  $client_id = variable_get('spotify_client_id');
  $client_secret = variable_get('spotify_client_secret');
  $user_id = variable_get('spotify_user_id');
  $playlist_id_selection = variable_get('spotify_playlist_id_selection');
  
  require '/home/mazpes5/www/rocola/sites/all/libraries/vendor/autoload.php';
  
  $session = new SpotifyWebAPI\Session($client_id, $client_secret);
  $api = new SpotifyWebAPI\SpotifyWebAPI();
  
  $session->requestCredentialsToken();
  $accessToken = $session->getAccessToken();
  $api->setAccessToken($accessToken);
  // user id 1295210986
  //playlist id 2yXxrkr6EyAA1MNPEDfSnf
  $playlistTracks = $api->getUserPlaylistTracks($user_id, $playlist_id_selection);
  $output .= '<table class="table table-hover">';
  $output .= '<tbody>';
  
  foreach ($playlistTracks->items as $track) {
    $track = $track->track;
    
    $output .= '<tr>';
    $output .= '<td>';
    $output .= '<a href="' . $track->external_urls->spotify . '">' . 
        '<img src="' . $track->album->images[0]->url .'" class="img-responsive img-thumbnail" '
        . 'alt="" height="204" width="136"> ' . $track->artists[0]->name . ' - ' 
        . $track->name . ' - ' . $track->id . '</a>';
    //print_r($track->album->images[0]->url);
    $output .= '</td>';
    $output .= '</tr>';
  }
  $output .= '</tbody>';
  $output .= '</table>';
  
  return $output;
  
}
